---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Data

```{r}
# load german football-league (Bundesliga) data
library("ordBTL")
library("wikibooks")
data(Bundesliga)
str(Bundesliga)

# add new variable Y3 reflecting the response which is coded as 
# 1 if the home team wins
# 2 if the game ends up with a tie
# 3 if the home team loses
diff = Bundesliga$Tore.Heim - Bundesliga$Tore.Gast
Bundesliga$Y3 = as.ordered(ifelse(diff >= 1, 1, ifelse(diff <= -1, 3, 2)))
buli0506 = subset(Bundesliga, Saison=="2005/2006")
str(buli0506)
```

## Estimate the team ability

As the bradley-terry model is just a logit model (binary target), we can extend this for multiclass target using, e.g., a cummulative logit model.
The `ordBTL` function does exactly this and uses internally the `VGAM` package.

```{r}
# Create design matrix for ordinal Bradley-Terry model
des.nohome = design(buli0506, var1="Heim", var2="Gast",
  use.vars="Y3", home.advantage="no", reference="GAMMA.MSV.Duisburg")

# first game is bayern vs. moenchengladbach
buli0506[1,]
# the design-matrix for the ordinal BTL model looks like this
des.nohome[1,]

mod.nohome = ordBTL(Y3~., data=des.nohome)
# team 'abilities' (should be approximately the ranking of the final standings)
getRank(mod.nohome, prefix="GAMMA", reference="GAMMA.MSV.Duisburg")

# for more examples see ?ordBTL
```

